### ISSUE TITLE
Nodenv not able to download iojs

### ISSUE THREAD

**Issue by JannKleen** [pre-commit/mirrors-coffeelint#3]
There seems to be a problem in nodeenv because iojs blocked downloading with the nodenv browser signature.

see https://github.com/ekalinin/nodeenv/issues/125 for more details

**Comment by ekalinin** [comment]
Seems to be fixed.

**Comment by JannKleen** [comment]
yep, I don't have any issues anymore :+1:
Thanks a lot for the very quick help @ekalinin
